project:
  title: ipardalis.com
  type: hugo
  output-dir: public
  render: 
    - content/wildlife-organizations-and-educational-initiatives/index.qmd

format: 
  hugo-md:
    code-fold: true
  
execute: 
  warning: false

bibliography: references.bib
toc: true