baseurl = "https://ipardalis.com/"
title = "iPardalis - Yellow Body Blue Bar Panther Chameleons for sale. Panther chameleons for sale near me."
theme = "hugo-universal-theme"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "ipardalis-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-144013109-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "For Sale"
    identifier = "sales"
    url  = "/babies/index"
    weight = 2
    
[[menu.main]]
    name = "Available Now!"
    url  = "/babies/available"
    parent = "sales"
    weight = 1

[[menu.main]]
    name = "Upcoming Clutches"
    url  = "/babies/upcoming"
    parent = "sales"
    weight = 2

[[menu.main]]
    name = "Ambilobe"
    identifier = "ambilobe"
    url  = "/ambilobe/"
    weight = 3
    
[[menu.main]]
    name = "Active"
    url = "/categories/ambilobe/"
    parent = "ambilobe"
    weight = 1

[[menu.main]]
    name = "Retired"
    url = "/categories/retired-ambilobe/"
    parent = "ambilobe"
    weight = 2

[[menu.main]]
    name = "Past Clutches"
    url = "/categories/past-clutches/"
    parent = "ambilobe"
    weight = 3

[[menu.main]]
    name = "Lineage Pics"
    url = "/categories/lineage/"
    parent = "ambilobe"
    weight = 4

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 4

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 5
    
[[menu.main]]
    name = "Terms"
    identifier = "tos"
    url  = "/tos/"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/Dripdrop12"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/jonmarkhill"
    pre = "<i class='fa fa-2x fa-facebook'></i>"
    
[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jonmarkhill/"
    pre = "<i class='fa fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/Dripdrop214"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:jon.mark.hill@ipardalis.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Jonathan Mark Hill"
    defaultKeywords = ["Panther Chameleons for sale", "Ambilobe", 
      "Yellow Body Blue Bar Ambilobe", "YBBB", "OBBB", "iPardalis", "juvenile panther chameleon",
      "Lesser chameleon", "Furcifer minor"
      ]
    defaultDescription = """\
      Panther chameleons for sale. Furcifer pardalis, \
      Ambilobe, furcifer minor, ball pythons, pituophis deppei jani,\
      Northern Mexican Pine Snakes, Mandarin Rat Snakes, \
      and other exotic reptiles. Panther chameleons near me.
      """

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyAb_MQa8J2AgFfZG6U-qv-b1B0CcoJyGKQ"
    
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "jon.mark.hill@ipardalis.com"

    about_us = "<p>Individually-raised Panther Chameleons. We're on our 4th generation of Ambilobe and 1st gen of Furcifer minor (Lesser Chameleons).</p>"
    copyright = "Copyright (c) 2020, Jonathan Mark Hill; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>Jonathan Mark Hill</strong>
        <br>17011 Hillard Street
        <br>Poolesville, MD 20837
        <br>
        <strong>USA</strong>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us via social media or email</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false

[params.see_more]
    enable = true
    icon = "fa fa-hand-o-down"
    title = "We have new clutches available"
    subtitle = "Do you want to see more?"
    link_url = "/babies/available/"
    link_text = "Check out the babies"

[params.clients]
    enable = false

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "We breed and raise Ambilobe Panther Chameleons (Fucifer pardalis), among other exotic reptiles. Our blog is a way to connect with the community and share our experience."

[imaging]
    quality = 25 