[context.deploy-preview.environment]
  HUGO_VERSION = "0.107.0"

[context.production.environment]
  HUGO_VERSION = "0.107.0"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/babies/available"
  to = "/panther-chameleons-for-sale"
  status = 301
  force = true
  query = {path = ":path"} #  apply this rule for /old-path?path=example
  conditions = {Language = ["en","es"], Country = ["US"]}